# Generated by Django 5.1.1 on 2025-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerodha_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('AdjClose', models.FloatField()),
                ('Close', models.FloatField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Open', models.FloatField()),
                ('volume', models.IntegerField()),
                ('Ticker', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='stockDataTable',
        ),
    ]
